// Copies the CINDERFALL web game (../public/game) into ./www, which Capacitor
// uses as its webDir. The game uses only relative asset paths, so it runs
// unchanged from the wrapper's root origin. Run automatically on install and
// before every `cap add` / `cap sync`.
//
// Node 16.7+ (fs.cp) — no external dependencies.

import { cp, rm, mkdir, access, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative, sep } from 'node:path';
import { admobIds } from './admob-ids.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '..', '..', 'public', 'game');
const DEST = resolve(here, '..', 'www');

try {
  await access(SRC);
} catch {
  console.error(`[sync-www] source not found: ${SRC}`);
  process.exit(1);
}

// Resolve the ad ids first: a bad or half-set pair (or test ids in a store
// build) should stop the build before anything is copied.
const ads = { android: admobIds('android'), ios: admobIds('ios') };

// Left out of the app bundle, as paths relative to public/game:
//   sw.js — Capacitor serves the files locally, and a service worker would be
//     a second caching layer over the native WebView.
//   *.md, and the store-only art (the PWA install screenshots and the 1024px
//     icon source) — nothing in the app loads them, and together they were
//     about half of the copied bundle.
// The PWA manifest stays: index.html links it, and a missing file there is a
// console error on every launch for the sake of a few hundred bytes.
const SKIP = new Set(['sw.js', 'assets/icon-1024.png', 'assets/screenshot-1.png', 'assets/screenshot-2.png']);
const skipped = (src) => {
  const rel = relative(SRC, src).split(sep).join('/');
  return SKIP.has(rel) || rel.endsWith('.md');
};

await rm(DEST, { recursive: true, force: true });
await mkdir(DEST, { recursive: true });
await cp(SRC, DEST, { recursive: true, filter: (src) => !skipped(src) });

// The ids the game requests ads with. The committed ads-config.js carries
// Google's test ids; it is only rewritten here, in the bundle, and only when
// real ones were supplied.
if (!ads.android.test || !ads.ios.test) {
  const entry = (p) => `{ appId: ${JSON.stringify(p.appId)}, rewarded: ${JSON.stringify(p.rewarded)}, testing: ${p.test} }`;
  await writeFile(
    resolve(DEST, 'js', 'engine', 'ads-config.js'),
    `// Generated by mobile/scripts/sync-www.mjs from ADMOB_* — do not edit.\n` +
    `export const ADS_CONFIG = {\n  android: ${entry(ads.android)},\n  ios: ${entry(ads.ios)},\n};\n`,
  );
}

console.log(`[sync-www] copied game → ${DEST}` +
  ` (ads: android ${ads.android.test ? 'TEST' : 'real'}, ios ${ads.ios.test ? 'TEST' : 'real'})`);
